### ISSUE TITLE
Migrate to Flutter 2 with sound null-safety

### ISSUE THREAD

**Issue by saileshbro** [ibhavikmakwana/FlutterPlayground#24]
Since flutter 2 is out we can migrate the project to use latest null safety feature and refactor the deprecated widgets.

**Comment by saileshbro** [comment]
@ibhavikmakwana You can assign me this I can work on this.

**Comment by ibhavikmakwana** [comment]
Sure @saileshbro You can work on it.

**Comment by saileshbro** [comment]
Hey @ibhavikmakwana can you review this?
