### ISSUE TITLE
Please upload to google play & app store

### ISSUE THREAD

**Issue by eladcandroid** [ibhavikmakwana/FlutterPlayground#6]

**Comment by Purus** [comment]
If you are fine, I can host it in Google Play Store.

**Comment by ibhavikmakwana** [comment]
Will soon upload it to play store :-)
Thanks @Purus.

**Comment by ibhavikmakwana** [comment]
It's up on the play store.
Can not upload it on the app store as of now.

https://play.google.com/store/apps/details?id=com.ibhavikmakwana.flutterplayground&hl=en
