### ISSUE TITLE
Not building with latest Flutter 1.2

### ISSUE THREAD

**Issue by bertbeck** [ibhavikmakwana/FlutterPlayground#7]
I tried building for IOS 9, 10 and 11 

 ** BUILD FAILED **

Xcode's output:
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code
    with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc
    Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: targeted OS version does not support use of thread local variables in
    __ZN9GMSx_absl18container_internal21ShouldInsertBackwardsEmPa for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by hansemannn** [comment]
Make sure your minimum deployment target is iOS 9+.
